# PKI paths
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/lighthouse.neb.zerus.org.crt
  key: /etc/nebula/lighthouse.neb.zerus.org.key

# Port settings
listen:
  #Default for this key is 0.0.0.0 which is v4-only and stupid
  host: 0.0.0.0
  port: 4242

# No static hosts for lighthouses
static_host_map:

#Lighthouse settings
lighthouse:
  am_lighthouse: true
  # Enable serving DNS to anyone (Even our external IP)
  serve_dns: true
  dns:
    host: 0.0.0.0
    port: 53

#Firewall settings
firewall:
  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any
    # Allow DNS incoming since we are serving DNS at this lighthouse
    - port: 53
      proto: udp
      group: any
    - port: any
      proto: tcp
      host: any
#I can also be a relay
relay:
  am_relay: true
